/*
 * File: app/view/achView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.achView', {
    extend: 'Ext.Container',
    alias: 'widget.achView',

    requires: [
        'Ext.Button',
        'Ext.Label',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        items: [
            {
                xtype: 'button',
                baseCls: 'backButton',
                border: '',
                bottom: '0px',
                docked: 'bottom',
                height: '65px',
                html: 'zurück',
                id: 'achBackButton',
                styleHtmlContent: true,
                width: 65,
                text: 'zurück'
            },
            {
                xtype: 'button',
                baseCls: 'backButton',
                border: '',
                bottom: '0px',
                centered: false,
                disabled: false,
                height: '65px',
                hidden: false,
                html: 'Karte',
                id: 'scoreButton',
                right: '0px',
                styleHtmlContent: true,
                width: 65,
                text: 'score'
            },
            {
                xtype: 'container',
                height: '80%',
                id: 'wrapper_achievments_forms',
                top: '50px',
                width: '100%',
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        height: '60px',
                        id: 'dailygoals_container',
                        margin: '5px',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                baseCls: 'uppercaseHeadline',
                                height: '25px',
                                html: 'Tagesziele',
                                id: 'locations_visited1',
                                margin: '5px'
                            },
                            {
                                xtype: 'dataview',
                                baseCls: 'dailyGoalsCounterDataView',
                                height: '41px',
                                id: 'abc',
                                width: '90%',
                                scrollable: false,
                                itemTpl: [
                                    '<div class="itemWrapper"><div class="content">Erreichte Tagesziele</div><div class="dailyGoalsCounterIcon">{id}</div></div>'
                                ],
                                maxItemCache: 1
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: '80px',
                        id: 'locations_visited_container',
                        margin: '5px',
                        top: '25px',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                baseCls: 'uppercaseHeadline',
                                height: '25px',
                                html: 'Sehenswürdigkeiten:',
                                id: 'locations_visited',
                                margin: '5px'
                            },
                            {
                                xtype: 'dataview',
                                baseCls: 'weekendTasksDoneDataview',
                                height: '167px',
                                id: 'weekendTasksDone',
                                width: '90%'
                            },
                            {
                                xtype: 'label',
                                baseCls: 'textCenterSmall',
                                height: '25px',
                                html: 'Bisher erreichte Erfolge und erledigte Aufgaben',
                                id: 'achievments_description',
                                margin: '5px',
                                top: '210px'
                            },
                            {
                                xtype: 'label',
                                baseCls: 'uppercaseHeadline',
                                height: '25px',
                                html: 'Abgefahrenes Busnetz:',
                                id: 'locations_visited2',
                                margin: '5px',
                                top: '250px'
                            },
                            {
                                xtype: 'label',
                                baseCls: 'netzanteilProgress',
                                docked: 'top',
                                height: '35px',
                                id: 'netzanteil',
                                top: '280px',
                                tpl: [
                                    '<div class="itemWrapper"><div id="percentage" class="percentIcon"><span id="int">{percent}</span><span id="typo">%</span></div><div class="content">des Busnetzes wurden bisher besucht.</div></div>'
                                ],
                                width: '100%'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                baseCls: 'orangeBorder',
                bottom: '30px',
                docked: 'bottom',
                id: 'border_bottom',
                left: '65px',
                width: '190px'
            },
            {
                xtype: 'image',
                height: '100%',
                id: 'achievment_bg',
                src: 'resources/images/background/achievements.png'
            }
        ]
    }

});