/*
 * File: app/view/achView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.achView', {
    extend: 'Ext.Container',
    alias: 'widget.achView',

    requires: [
        'Ext.Button',
        'Ext.Container',
        'Ext.Label',
        'Ext.field.Checkbox',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        items: [
            {
                xtype: 'button',
                baseCls: 'backButton',
                border: '',
                bottom: '0px',
                docked: 'bottom',
                height: '65px',
                html: 'zurück',
                id: 'achBackButton',
                styleHtmlContent: true,
                width: 65,
                text: 'zurück'
            },
            {
                xtype: 'button',
                baseCls: 'backButton',
                border: '',
                bottom: '0px',
                centered: false,
                disabled: false,
                height: '65px',
                hidden: false,
                html: 'Punkte',
                id: 'scoreButton',
                right: '0px',
                styleHtmlContent: true,
                width: 65,
                text: 'score'
            },
            {
                xtype: 'container',
                height: '80%',
                id: 'wrapper_achievments_forms',
                top: '50px',
                width: '100%',
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        height: '60px',
                        id: 'netzerkundung_container',
                        items: [
                            {
                                xtype: 'label',
                                height: '25px',
                                html: '<p>Netzerkundung:</p>',
                                id: 'netzerkundung',
                                margin: '5px'
                            },
                            {
                                xtype: 'checkboxfield',
                                label: 'Field'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: '80px',
                        id: 'locations_visited_container',
                        top: '25px',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                height: '25px',
                                html: '<p>Orte besucht:</p>',
                                id: 'locations_visited',
                                margin: '5px'
                            },
                            {
                                xtype: 'checkboxfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'checkboxfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'checkboxfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'label',
                                baseCls: 'achievementsTextSmall',
                                height: '25px',
                                html: 'Bisher erreichte Erfolge und erledigte Aufgaben',
                                id: 'achievments_description',
                                margin: '5px',
                                top: '150px'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                baseCls: 'orangeBorder',
                bottom: '30px',
                docked: 'bottom',
                id: 'border_bottom',
                left: '65px',
                width: '190px'
            },
            {
                xtype: 'image',
                height: '100%',
                id: 'achievment_bg',
                src: 'resources/images/background/achievements.png'
            }
        ]
    }

});