/*
 * File: app/view/fahrplaner.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.fahrplaner', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Search',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'image',
                id: 'netzBackground',
                src: 'resources/images/background/verbindungen.png'
            },
            {
                xtype: 'container',
                height: 110,
                id: 'inputOrt',
                width: 320,
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'inputfields',
                        items: [
                            {
                                xtype: 'searchfield',
                                id: 'startort',
                                label: 'Start',
                                autoCorrect: true,
                                placeHolder: 'Aktueller Ort'
                            },
                            {
                                xtype: 'searchfield',
                                id: 'ziel',
                                label: 'Ziel',
                                autoCorrect: true,
                                placeHolder: 'Zielort'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'top',
                height: 348,
                id: 'linienInformationen',
                top: 140,
                width: '100%',
                scrollable: 'horizontal',
                items: [
                    {
                        xtype: 'dataview',
                        docked: 'top',
                        height: 100,
                        id: 'lineOne',
                        style: 'background-color: rgba(255,255,255, 0.6);',
                        width: '100%',
                        scrollable: false,
                        itemTpl: [
                            '<div>Data View Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'dataview',
                        docked: 'top',
                        height: 100,
                        id: 'lineTwo',
                        margin: '10 0 0 0 ',
                        style: 'background-color: rgba(255,255,255, 0.6);',
                        width: '100%',
                        scrollable: false,
                        itemTpl: [
                            '<div>Data View Item {string}</div>'
                        ]
                    },
                    {
                        xtype: 'dataview',
                        docked: 'top',
                        height: 100,
                        id: 'lineThree',
                        margin: '10 0 0 0',
                        style: 'background-color: rgba(255,255,255, 0.6);',
                        width: '100%',
                        scrollable: false,
                        itemTpl: [
                            '<div>Data View Item {string}</div>'
                        ]
                    }
                ]
            }
        ]
    }

});