/*
 * File: app/view/goalsDetails.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.goalsDetails', {
    extend: 'Ext.Container',

    alternateClassName: [
        'backButton'
    ],
    requires: [
        'Ext.Button',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        id: 'goals1',
        width: '100%',
        items: [
            {
                xtype: 'container',
                centered: true,
                docked: 'top',
                height: '100%',
                id: 'container_details_view',
                style: 'padding-top:60px;',
                width: '320px',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        baseCls: 'orangeBorder',
                        bottom: '30px',
                        id: 'details_border_bottom',
                        width: '255px'
                    },
                    {
                        xtype: 'button',
                        baseCls: 'backButton',
                        border: '',
                        bottom: '0px',
                        centered: false,
                        disabled: false,
                        docked: 'bottom',
                        height: '65px',
                        hidden: false,
                        html: '<span>zurück</span>',
                        id: 'detailsBackButton',
                        right: '0px',
                        styleHtmlContent: true,
                        width: 65,
                        text: 'back'
                    },
                    {
                        xtype: 'dataview',
                        height: '100px',
                        id: 'dataview_details',
                        top: '25px',
                        width: '100%',
                        emptyText: 'Besuche den Löwenpudel',
                        itemTpl: [
                            '<div><h1>{name}</h1><p>{description}</p></div>'
                        ],
                        maxItemCache: 3,
                        store: 'sights'
                    }
                ]
            },
            {
                xtype: 'image',
                centered: false,
                docked: 'top',
                height: '100%',
                id: 'details_background',
                width: '320px',
                src: 'resources/images/background/game.png'
            }
        ]
    }

});