/*
 * File: app/view/goalsView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.goalsView', {
    extend: 'Ext.Container',
    alias: 'widget.goalsView',

    requires: [
        'Ext.Button',
        'Ext.Label',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        id: 'goals',
        width: '100%',
        items: [
            {
                xtype: 'container',
                centered: true,
                docked: 'top',
                height: '100%',
                id: 'container_goal_view',
                style: 'padding-top:60px;',
                width: '320px',
                layout: 'fit',
                items: [
                    {
                        xtype: 'container',
                        baseCls: 'orangeBorder',
                        bottom: '30px',
                        id: 'goals_border_bottom',
                        width: '255px'
                    },
                    {
                        xtype: 'button',
                        baseCls: 'backButton',
                        border: '',
                        bottom: '0px',
                        centered: false,
                        disabled: false,
                        docked: 'bottom',
                        height: '65px',
                        hidden: false,
                        html: '<span>zurück</span>',
                        id: 'goalsBackButton',
                        right: '0px',
                        styleHtmlContent: true,
                        width: 65,
                        text: 'back'
                    },
                    {
                        xtype: 'container',
                        centered: false,
                        id: 'goals_wrapper',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'container',
                                docked: 'top',
                                height: '100px',
                                id: 'daily_goals',
                                margin: '5px',
                                top: '10px',
                                width: '100%',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'label',
                                        baseCls: 'uppercaseHeadline',
                                        height: '25px',
                                        html: '<p>Besuche folgende Haltestelle:</p>',
                                        id: 'label_daily_goals'
                                    },
                                    {
                                        xtype: 'list',
                                        baseCls: 'dailyGoalsDataView',
                                        height: '42px',
                                        hidden: false,
                                        id: 'sightsDaily',
                                        top: '25px',
                                        width: '90%',
                                        itemCls: 'sights_list',
                                        itemTpl: [
                                            '<div>{name}</div>'
                                        ],
                                        store: 'stops'
                                    },
                                    {
                                        xtype: 'label',
                                        baseCls: 'textCenterSmall',
                                        height: '25px',
                                        html: '<p>Besuche folgende Haltestelle in der angegebenen Zeit und verdiene dir dadurch eine <span class="bold">Medallie</span>!</p>',
                                        id: 'dailyGoalsDescribtion',
                                        style: 'text-align:left;',
                                        top: '78px'
                                    },
                                    {
                                        xtype: 'label',
                                        height: '25px',
                                        html: '<p>Verbleibende Zeit:</p>',
                                        id: 'dailyGoalsLabel',
                                        top: '115px'
                                    },
                                    {
                                        xtype: 'label',
                                        baseCls: 'textCenterSmall',
                                        height: '25px',
                                        html: '<p>6 Stunden 23 Minuten</p>',
                                        id: 'dailyGoalsCounter',
                                        top: '140px'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                docked: 'top',
                                height: '100px',
                                id: 'weekly_goals',
                                margin: '5px',
                                top: '185px',
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        baseCls: 'uppercaseHeadline',
                                        height: '25px',
                                        html: '<p>Sehenswürdigkeiten:</p>',
                                        id: 'label_weekly_goals'
                                    },
                                    {
                                        xtype: 'list',
                                        baseCls: 'dailyGoalsDataView',
                                        height: '175px',
                                        id: 'dataview_weekly_goals',
                                        top: '25px',
                                        width: '90%',
                                        itemCls: 'sights_list',
                                        itemTpl: [
                                            '<div>{name}</div>'
                                        ],
                                        store: 'sights'
                                    },
                                    {
                                        xtype: 'label',
                                        baseCls: 'textCenterSmall',
                                        height: '25px',
                                        html: '<p>Suche dir von den aufgelisteten Sehenswürdigkeiten eine aus und verdiene dir durch den Besuch einen <span class="bold">Pokal</span></p>',
                                        id: 'weeklyGoalsDescribtion',
                                        style: 'text-align:left;',
                                        top: '215px'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'image',
                centered: false,
                docked: 'top',
                height: '100%',
                id: 'goals_background',
                width: '320px',
                src: 'resources/images/background/game.png'
            }
        ]
    }

});