/*
 * File: app/view/InitialView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.InitialView', {
    extend: 'Ext.Container',

    requires: [
        'VosNavigator.view.mainScreen',
        'VosNavigator.view.searchView',
        'VosNavigator.view.fahrplanerView',
        'VosNavigator.view.goalsView',
        'VosNavigator.view.settingsView',
        'VosNavigator.view.weckerView',
        'VosNavigator.view.achView',
        'VosNavigator.view.goalsDetails',
        'VosNavigator.view.mapView',
        'Ext.Container'
    ],

    config: {
        fullscreen: true,
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'mainScreen',
                id: 'MainView'
            },
            {
                xtype: 'searchview',
                hidden: true
            },
            {
                xtype: 'fahrplanerview',
                hidden: true,
                id: 'FahrplanerView'
            },
            {
                xtype: 'goalsview',
                hidden: true,
                id: 'GoalsView'
            },
            {
                xtype: 'settingsview',
                hidden: true,
                id: 'SettingsView'
            },
            {
                xtype: 'weckerview',
                hidden: true,
                id: 'WeckerView'
            },
            {
                xtype: 'achView',
                hidden: true,
                id: 'AchView'
            },
            {
                xtype: 'goalsdetails',
                hidden: true
            },
            {
                xtype: 'mapView',
                hidden: true,
                id: 'MapView'
            }
        ]
    }

});