/*
 * File: app/view/mainScreen.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.mainScreen', {
    extend: 'Ext.Container',
    alias: 'widget.mainScreen',

    requires: [
        'Ext.Img',
        'Ext.Container',
        'Ext.Button'
    ],

    config: {
        height: '100%',
        id: 'mainWrapper',
        width: '100%',
        items: [
            {
                xtype: 'image',
                centered: false,
                height: '100%',
                hidden: false,
                id: 'background',
                width: '100%',
                src: 'resources/images/background/std_bg.png'
            },
            {
                xtype: 'container',
                height: '60px',
                id: 'logo',
                style: 'display:block;\nbackground-color: rgba(255,255,255, 0.7);\npadding:0px;\nmargin:0px;',
                styleHtmlContent: true,
                width: '320px',
                items: [
                    {
                        xtype: 'image',
                        docked: 'top',
                        height: '50px',
                        id: 'vosLogo',
                        style: 'margin:0px;\npadding:0px;',
                        styleHtmlContent: true,
                        top: '5px',
                        width: '320px',
                        src: 'resources/images/logo/vos_navigator.png'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'button_cont',
                items: [
                    {
                        xtype: 'container',
                        height: 160,
                        id: 'wecker',
                        left: 5,
                        top: 35,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: 70,
                                hidden: false,
                                id: 'WeckerImage',
                                left: 15,
                                style: 'oacity:0.9;',
                                top: -3,
                                width: 70,
                                src: 'resources/images/button_png/wecker.png'
                            },
                            {
                                xtype: 'image',
                                centered: false,
                                height: 70,
                                hidden: true,
                                id: 'WeckerImageInv',
                                left: 15,
                                style: 'opacity:0.9;',
                                top: -3,
                                width: 70,
                                src: 'resources/images/button_png/wecker_inv.png'
                            },
                            {
                                xtype: 'button',
                                height: 70,
                                hidden: false,
                                id: 'weckerButton',
                                left: 15,
                                style: '-webkit-border-radius: 100%;\nborder-radius: 100%; /* border radius */\n-webkit-background-clip: padding-box;\nbackground-clip: padding-box; /* prevents bg color from leaking outside the border */\nbackground-color: fff;\ndisplay:block;\nfont-size:11px;\nopacity:0.0;',
                                styleHtmlContent: true,
                                top: -3,
                                width: 70,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 100,
                        id: 'einstellungen',
                        left: 165,
                        top: 70,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: 70,
                                hidden: false,
                                id: 'SettingsImage',
                                left: 15,
                                style: 'opacity:0.9;',
                                width: 70,
                                src: 'resources/images/button_png/settings.png'
                            },
                            {
                                xtype: 'image',
                                height: 70,
                                hidden: true,
                                id: 'SettingsImageInv',
                                left: 15,
                                style: 'opacity:0.9;',
                                width: 70,
                                src: 'resources/images/button_png/settings_inv.png'
                            },
                            {
                                xtype: 'button',
                                height: 70,
                                id: 'settingsButton',
                                left: 15,
                                style: '-webkit-border-radius: 100%;\nborder-radius: 100%; /* border radius */\n-webkit-background-clip: padding-box;\nbackground-clip: padding-box; /* prevents bg color from leaking outside the border */\nbackground-color: fff;\ndisplay:block;\nfont-size:11px;\nopacity:0.0;',
                                styleHtmlContent: true,
                                top: 0,
                                width: 70,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 87,
                        hidden: false,
                        id: 'achievements',
                        left: 90,
                        top: 365,
                        width: 180,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: 70,
                                hidden: false,
                                id: 'AchImage',
                                left: 110,
                                style: 'opacity:0.9;',
                                top: 20,
                                width: 70,
                                src: 'resources/images/button_png/ach.png'
                            },
                            {
                                xtype: 'image',
                                height: 70,
                                hidden: true,
                                id: 'AchImageInv',
                                left: 110,
                                style: 'opacity:0.9;',
                                top: 20,
                                width: 70,
                                src: 'resources/images/button_png/ach_inv.png'
                            },
                            {
                                xtype: 'button',
                                height: 70,
                                id: 'achieveButton',
                                left: 110,
                                style: '-webkit-border-radius: 100%;\nborder-radius: 100%; /* border radius */\n-webkit-background-clip: padding-box;\nbackground-clip: padding-box; /* prevents bg color from leaking outside the border */\nbackground-color: fff;\ndisplay:block;\nfont-size:11px;\nopacity:0.0;',
                                styleHtmlContent: true,
                                top: 20,
                                width: 70,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 98,
                        hidden: false,
                        id: 'gameContainer',
                        left: 10,
                        top: 300,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: 70,
                                hidden: false,
                                id: 'GameImage',
                                left: 6,
                                style: 'opacity:0.9;',
                                top: 30,
                                width: 70,
                                src: 'resources/images/button_png/game.png'
                            },
                            {
                                xtype: 'image',
                                height: 70,
                                hidden: true,
                                id: 'GameImageInv',
                                left: 6,
                                style: 'opacity:0.9;',
                                top: 30,
                                width: 70,
                                src: 'resources/images/button_png/game_inv.png'
                            },
                            {
                                xtype: 'button',
                                height: 70,
                                id: 'game',
                                left: 6,
                                style: '-webkit-border-radius: 100%;\nborder-radius: 100%; /* border radius */\n-webkit-background-clip: padding-box;\nbackground-clip: padding-box; /* prevents bg color from leaking outside the border */\nbackground-color: fff;\ndisplay:block;\nfont-size:11px;\nopacity:0.0;',
                                styleHtmlContent: true,
                                top: 30,
                                width: 70,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 124,
                        id: 'start',
                        left: 98,
                        top: 195,
                        width: 124,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: false,
                                id: 'StartImage',
                                style: 'opacity:0.9;\ndisplay:block;',
                                top: 0,
                                width: '100%',
                                src: 'resources/images/button_png/start.png'
                            },
                            {
                                xtype: 'image',
                                height: '100%',
                                hidden: true,
                                id: 'StartImageInv',
                                style: 'opacity:0.9;',
                                top: 0,
                                width: '100%',
                                src: 'resources/images/button_png/start_inv.png'
                            },
                            {
                                xtype: 'button',
                                action: 'start',
                                height: '100%',
                                id: 'StartButton',
                                style: '-webkit-border-radius: 100%;\nborder-radius: 100%; /* border radius */\n-webkit-background-clip: padding-box;\nbackground-clip: padding-box; /* prevents bg color from leaking outside the border */\nbackground-color: fff;\ndisplay:block;\nfont-size:11px;\nopacity:0.0;',
                                styleHtmlContent: true,
                                top: 0,
                                width: '100%',
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ]
    }

});