/*
 * File: app/view/main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.main', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Img',
        'Ext.Container'
    ],

    config: {
        fullscreen: true,
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'image',
                centered: false,
                hidden: false,
                id: 'background',
                width: '100%',
                src: 'resources/images/background/std_bg.png'
            },
            {
                xtype: 'container',
                height: '60px',
                id: 'logo',
                style: 'display:block;\nbackground-color: rgba(255,255,255, 0.7);\npadding:0px;\nmargin:0px;',
                styleHtmlContent: true,
                width: '320px',
                items: [
                    {
                        xtype: 'image',
                        docked: 'top',
                        height: '50px',
                        id: 'vosLogo',
                        style: 'margin:0px;\npadding:0px;',
                        styleHtmlContent: true,
                        top: '5px',
                        width: '320px',
                        src: 'resources/images/logo/vos_navigator.png'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'button_cont',
                items: [
                    {
                        xtype: 'container',
                        height: 160,
                        id: 'weckerButton',
                        left: 30,
                        top: 75,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                id: 'button',
                                width: '100%',
                                src: 'resources/images/button_png/Wecker.png'
                            },
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: true,
                                id: 'button_inv',
                                width: '100%',
                                src: 'resources/images/button_png/Wecker_inv.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 100,
                        id: 'einstellungen',
                        left: 165,
                        top: 130,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: false,
                                id: 'einst_button',
                                width: '100%',
                                src: 'resources/images/button_png/Einstellungen.png'
                            },
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: true,
                                id: 'einst_buttonInv',
                                width: '100%',
                                src: 'resources/images/button_png/Einstellungen_inv.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 87,
                        hidden: false,
                        id: 'achievements',
                        left: 110,
                        top: 400,
                        width: 180,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                id: 'achie_button',
                                width: '100%',
                                src: 'resources/images/button_png/Achievments.png'
                            },
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: true,
                                id: 'achie_buttonInv',
                                width: '100%',
                                src: 'resources/images/button_png/Achievments_inv.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 98,
                        hidden: false,
                        id: 'game',
                        left: 40,
                        top: 335,
                        width: 100,
                        items: [
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                id: 'game_button',
                                width: '100%',
                                src: 'resources/images/button_png/Game.png'
                            },
                            {
                                xtype: 'image',
                                centered: true,
                                height: '100%',
                                hidden: true,
                                id: 'game_buttonInv',
                                width: '100%',
                                src: 'resources/images/button_png/Game_inv.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 124,
                        id: 'start',
                        itemId: 'mycontainer2',
                        left: 98,
                        top: '222px',
                        width: 124,
                        items: [
                            {
                                xtype: 'image',
                                hidden: false,
                                id: 'startbutton',
                                minHeight: '100%',
                                minWidth: '100%',
                                styleHtmlContent: true,
                                src: 'resources/images/button_png/start.png'
                            },
                            {
                                xtype: 'image',
                                height: '100%',
                                hidden: true,
                                id: 'startbuttonInv',
                                minHeight: '100%',
                                minWidth: '100%',
                                styleHtmlContent: true,
                                width: '100%',
                                src: 'resources/images/button_png/start_inv.png'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'startTab',
                event: 'tap',
                delegate: '#start'
            }
        ]
    },

    startTab: function(container) {
        startbuttonInv.show();
        alert("Start");
        startbuttonInv.hide();
    }

});