/*
 * File: app/view/mainScreen.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.mainScreen', {
    extend: 'Ext.Container',
    alias: 'widget.mainScreen',

    requires: [
        'Ext.Img',
        'Ext.Container',
        'Ext.Button'
    ],

    config: {
        baseCls: '',
        height: '100%',
        id: 'mainWrapper',
        width: '100%',
        items: [
            {
                xtype: 'image',
                centered: false,
                height: '100%',
                hidden: false,
                id: 'background',
                width: '100%',
                src: 'resources/images/background/std_bg.png'
            },
            {
                xtype: 'container',
                baseCls: 'transparentWhite',
                height: '60px',
                id: 'logo',
                styleHtmlContent: true,
                width: '320px',
                items: [
                    {
                        xtype: 'image',
                        baseCls: 'marginZeroPaddingZero',
                        docked: 'top',
                        height: '50px',
                        id: 'vosLogo',
                        styleHtmlContent: true,
                        top: '5px',
                        width: '320px',
                        src: 'resources/images/logo/vos_navigator.png'
                    }
                ]
            },
            {
                xtype: 'container',
                id: 'button_cont',
                items: [
                    {
                        xtype: 'container',
                        height: 160,
                        id: 'wecker',
                        left: 5,
                        top: 30,
                        width: 100,
                        items: [
                            {
                                xtype: 'button',
                                baseCls: 'roundTransparentBg',
                                height: 75,
                                id: 'weckerButton',
                                left: 10,
                                styleHtmlContent: true,
                                top: -5,
                                width: 75,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 100,
                        id: 'einstellungen',
                        left: 165,
                        top: 70,
                        width: 100,
                        items: [
                            {
                                xtype: 'button',
                                baseCls: 'roundTransparentBg',
                                height: 75,
                                id: 'settingsButton',
                                left: 15,
                                styleHtmlContent: true,
                                top: -7,
                                width: 75,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 87,
                        hidden: false,
                        id: 'achievements',
                        left: 90,
                        top: 365,
                        width: 180,
                        items: [
                            {
                                xtype: 'button',
                                baseCls: 'roundTransparentBg',
                                height: 75,
                                id: 'achieveButton',
                                left: 113,
                                styleHtmlContent: true,
                                top: 18,
                                width: 75,
                                labelCls: '',
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 98,
                        hidden: false,
                        id: 'gameContainer',
                        left: 10,
                        top: 300,
                        width: 100,
                        items: [
                            {
                                xtype: 'button',
                                baseCls: 'roundTransparentBg',
                                height: 75,
                                id: 'game',
                                left: 10,
                                styleHtmlContent: true,
                                top: 4,
                                width: 75,
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 124,
                        id: 'start',
                        left: 98,
                        top: 195,
                        width: 124,
                        items: [
                            {
                                xtype: 'button',
                                action: 'start',
                                baseCls: 'roundTransparentBg',
                                centered: true,
                                height: 120,
                                id: 'StartButton',
                                itemId: 'StartButton',
                                left: 1,
                                styleHtmlContent: true,
                                top: -2,
                                width: 120,
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ]
    }

});