/*
 * File: app/view/mapView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.mapView', {
    extend: 'Ext.Container',
    alias: 'widget.mapView',

    requires: [
        'Ext.Button',
        'Ext.Label',
        'Ext.Map',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        items: [
            {
                xtype: 'button',
                baseCls: 'backButton',
                border: '',
                bottom: '0px',
                centered: false,
                disabled: false,
                height: '65px',
                hidden: false,
                html: 'zurück',
                id: 'scoreButton1',
                right: '0px',
                styleHtmlContent: true,
                width: 65,
                text: 'score'
            },
            {
                xtype: 'container',
                height: '80%',
                id: 'contentMapWrapper',
                top: '50px',
                width: '100%',
                items: [
                    {
                        xtype: 'label',
                        baseCls: 'uppercaseHeadline',
                        docked: 'top',
                        html: 'Kartenübersicht',
                        id: 'mapHeadline',
                        margin: '5px'
                    },
                    {
                        xtype: 'container',
                        height: '430px',
                        id: 'mapContainer',
                        style: '',
                        items: [
                            {
                                xtype: 'map',
                                height: '360px',
                                itemId: 'mymap'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        baseCls: 'textCenterSmall',
                        docked: 'top',
                        html: 'Bereits besuchte Haltestellen sind in <span class="green bold">Grün</span> und noch nicht besuchte in <span class="red bold">Rot</span> gekennzeichnet.',
                        id: 'infoText',
                        top: '370px'
                    },
                    {
                        xtype: 'label',
                        baseCls: 'textCenterSmall',
                        docked: 'top',
                        height: '25px',
                        html: 'Du hast bereits <span class="bold">25%</span> des Busnetztes besucht...',
                        id: 'percent',
                        top: '410px',
                        width: '100%'
                    }
                ]
            },
            {
                xtype: 'container',
                baseCls: 'orangeBorder',
                bottom: '30px',
                docked: 'bottom',
                id: 'borderBottom',
                width: '255px'
            },
            {
                xtype: 'image',
                height: '100%',
                id: 'achievment_bg1',
                src: 'resources/images/background/achievements.png'
            }
        ]
    }

});