/*
 * File: app/view/settingsView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.settingsView', {
    extend: 'Ext.Container',
    alias: 'widget.settingsview',

    requires: [
        'Ext.Container',
        'Ext.Label',
        'Ext.Button',
        'Ext.field.Toggle',
        'Ext.field.Radio',
        'Ext.Img'
    ],

    config: {
        height: '100%',
        itemId: 'goals1',
        width: '100%',
        items: [
            {
                xtype: 'container',
                centered: true,
                docked: 'top',
                height: '100%',
                id: 'container_settings_view',
                style: 'padding-top:60px;',
                width: '320px',
                layout: 'fit',
                items: [
                    {
                        xtype: 'label',
                        baseCls: 'uppercaseHeadline',
                        height: '25px',
                        html: '<p>Einstellungen:</p>',
                        id: 'headline_settings',
                        margin: '5px'
                    },
                    {
                        xtype: 'container',
                        baseCls: 'orangeBorder',
                        bottom: '30px',
                        id: 'settings_border_bottom',
                        width: '255px'
                    },
                    {
                        xtype: 'button',
                        baseCls: 'backButton',
                        border: '',
                        bottom: '0px',
                        centered: false,
                        disabled: false,
                        docked: 'bottom',
                        height: '65px',
                        hidden: false,
                        html: '<span>zurück</span>',
                        id: 'settingsBackButton',
                        right: '0px',
                        styleHtmlContent: true,
                        width: 65,
                        text: 'back'
                    },
                    {
                        xtype: 'container',
                        centered: false,
                        id: 'settings_wrapper_container',
                        layout: 'fit'
                    },
                    {
                        xtype: 'container',
                        id: 'settings_form_wrapper',
                        top: '30px',
                        width: '100%',
                        items: [
                            {
                                xtype: 'togglefield',
                                label: 'Field'
                            },
                            {
                                xtype: 'radiofield',
                                label: 'Field',
                                name: 'field'
                            },
                            {
                                xtype: 'sliderfield',
                                id: 'gpsPace',
                                label: 'GPS Pace',
                                value: [
                                    30
                                ],
                                maxValue: 120,
                                minValue: 5
                            },
                            {
                                xtype: 'label',
                                html: 'Aktuelle Position wird im 30 Sekunden Takt überprüft.',
                                id: 'label_settings',
                                margin: '5px'
                            },
                            {
                                xtype: 'label',
                                baseCls: 'textCenterSmall',
                                html: '<p>Je häufiger die Position überprüft wird, desto mehr Strom wird verbraucht.</p>',
                                id: 'info',
                                margin: '5px'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'image',
                centered: false,
                docked: 'top',
                height: '100%',
                id: 'goals_background1',
                width: '320px',
                src: 'resources/images/background/settings.png'
            }
        ]
    }

});