/*
 * File: app/view/weckerView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.view.weckerView', {
    extend: 'Ext.Container',
    alias: 'widget.weckerview',

    requires: [
        'Ext.Img',
        'Ext.Container',
        'Ext.field.Toggle',
        'Ext.field.Select',
        'Ext.field.Checkbox',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        itemId: 'mycontainer1',
        items: [
            {
                xtype: 'image',
                height: '100%',
                id: 'wecker_bg',
                src: 'resources/images/background/wecker.png'
            },
            {
                xtype: 'container',
                centered: true,
                docked: 'top',
                height: '100%',
                margin: '10% 0',
                width: '100%'
            },
            {
                xtype: 'container',
                centered: true,
                height: '60%',
                id: 'menu',
                width: '100%',
                items: [
                    {
                        xtype: 'togglefield',
                        id: 'weckerOnOffSwitch',
                        width: '100%',
                        label: 'Wecker ein',
                        labelWidth: '75%',
                        name: 'toggle_alarm'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'selectTune',
                        label: 'Ton',
                        options: [
                            {
                                text: 'Super Mario Tune',
                                value: 'superMario.mp3'
                            },
                            {
                                text: 'The Legend of Zelda Tune',
                                value: 'zelda.mp3'
                            },
                            {
                                text: 'Monkey Island Tune',
                                value: 'monkeyIsland.mp3'
                            }
                        ]
                    },
                    {
                        xtype: 'checkboxfield',
                        id: 'shortestPath',
                        label: 'Kürzester Weg',
                        labelWidth: '80%',
                        name: 'link_verbindung'
                    },
                    {
                        xtype: 'togglefield',
                        id: 'mehrfachKlingelnOnOffSwitch',
                        label: 'Mehrfach klingeln',
                        labelWidth: '75%',
                        name: 'toggle_alarmStop'
                    },
                    {
                        xtype: 'label',
                        html: 'Alarm vor jedem Umstieg',
                        id: 'schriftzug',
                        styleHtmlContent: true
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        id: 'slider',
                        items: [
                            {
                                xtype: 'sliderfield',
                                id: 'weckRadius',
                                itemId: 'mysliderfield',
                                style: 'background: none;\nmargin-left: auto;\nmargin-right: auto;',
                                styleHtmlContent: true,
                                width: '90%',
                                label: '',
                                maxValue: 2000,
                                minValue: 200
                            },
                            {
                                xtype: 'label',
                                html: '200 m vor dem Zielpunkt',
                                id: 'sliderValueLabel',
                                style: 'text-align: center;',
                                styleHtmlContent: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                bottom: 0,
                height: 65,
                id: 'backButtonContainer1',
                width: '100%',
                items: [
                    {
                        xtype: 'button',
                        baseCls: 'backButton',
                        border: '',
                        bottom: '0px',
                        centered: false,
                        disabled: false,
                        docked: 'bottom',
                        height: '65px',
                        hidden: false,
                        html: '<span>zurück</span>',
                        id: 'weckerBackButton',
                        right: '0px',
                        styleHtmlContent: true,
                        width: 65,
                        text: 'back'
                    },
                    {
                        xtype: 'container',
                        bottom: '30px',
                        id: 'goals_border_bottom2',
                        style: 'background-color:rgba(211, 83, 0, 0.9);\ndisplay:block;\nheight:5px;\noverflow:hidden;',
                        width: '255px'
                    }
                ]
            }
        ]
    }

});