/*
 * File: app/controller/Achievements.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.controller.Achievements', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            achView: '#AchView',
            achBackButton: 'button#achBackButton',
            mainView: 'container#MainView',
            mapView: '#MapView'
        },

        control: {
            "button#achBackButton": {
                tap: 'achBackButton'
            },
            "button#scoreButton": {
                tap: 'onButtonTap'
            }
        }
    },

    achBackButton: function(button, e, eOpts) {
        this.getAchView().hide();
        this.getMainView().show();
    },

    onButtonTap: function(button, e, eOpts) {
        console.log("Map Button.");
        this.getAchView().hide();
        this.getMapView().show();
    }

});