/*
 * File: app/controller/Fahrplaner.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.controller.Fahrplaner', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            MainView: '#MainView',
            fahrplanerBackButton: '#fahrplanerBackButton',
            FahrplanerView: '#FahrplanerView',
            mybutton: 'button#mybutton',
            lineOne: 'dataview#lineOne',
            lineTwo: 'dataview#lineTwo',
            mysearchfield1: 'searchfield#mysearchfield1'
        },

        control: {
            "button#fahrplanerBackButton": {
                tap: 'fahrplanerBackButton'
            },
            "button#mybutton": {
                tap: 'storeTest'
            },
            "#lineOne": {
                itemtap: 'onLineOneItemTap'
            },
            "button#reset_button": {
                tap: 'onButtonTap'
            },
            "searchfield#mysearchfield1": {
                action: 'onMysearchfield1Action'
            }
        }
    },

    fahrplanerBackButton: function(button, e, eOpts) {
        this.getFahrplanerView().hide();
        this.getMainView().show();
    },

    storeTest: function(button, e, eOpts) {
        this.stops.filter("id", 250);
    },

    onLineOneItemTap: function(list, index, item, record) {
        var dataView = this.getLineTwo();
        var linesData = record.get('lines');
        //var quantity = linesArray.getCount();



        var myPanel = Ext.create('Ext.Panel', {
            html: "<div style=\"float:left;width:50%;background-color:green;\"><div style=\"float:left;width:15px;height:15px;background-image:url(resources/images/icons/bus-icon-150x150.png);background-size:15px 15px;\"></div> " + this.getLines(linesData) + "</div><div style=\"background-color:#5e5e5e;float:left;width:50%;\">"+ record.get('name')+ "</div>"
        });

        dataView.add([myPanel]);
    },

    onButtonTap: function(button, e, eOpts) {
        this.getLineTwo().removeAll();
    },

    onMysearchfield1Action: function() {
        var value = this.getMysearchfield1().getValue();
        var store = Ext.getStore('stops');
        store.filter('name', value);

        var dataView = this.getLineOne();

        dataView.refresh();

        console.log("Search refresh with: "+value);
    },

    getLines: function(data) {
        var len = data.length;
        var content = '';

        for(var i=0;i<len;i++){
            content += data[i]['LineId'];
            if(i != len-1){
                content += ", ";
            }
        }

        return content;
    }

});