/*
 * File: app/controller/Fahrplaner.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.controller.Fahrplaner', {
    extend: 'Ext.app.Controller',

    config: {
        startOrt: {
            lat: 0.0,
            lng: 0.0
        },
        zielOrt: {
            lat: 0.0,
            lng: 0.0
        },
        db: null,

        refs: {
            MainView: '#MainView',
            fahrplanerBackButton: '#fahrplanerBackButton',
            FahrplanerView: '#FahrplanerView',
            mybutton: 'button#mybutton',
            lineOne: 'dataview#lineOne',
            lineTwo: 'dataview#lineTwo',
            searchView: '#searchView',
            SearchTitle: 'label#SearchTitle',
            mybutton4: 'button#mybutton4'
        },

        control: {
            "button#fahrplanerBackButton": {
                tap: 'fahrplanerBackButton'
            },
            "button#mybutton": {
                tap: 'storeTest'
            },
            "#lineOne": {
                itemtap: 'onLineOneItemTap'
            },
            "searchfield#searchfieldStart": {
                focus: 'onFocusSearchfieldStart'
            },
            "searchfield#searchfieldDestination": {
                focus: 'onFocusSearchfieldDestination'
            },
            "button#mybutton4": {
                tap: 'sucheVerbindung'
            }
        }
    },

    fahrplanerBackButton: function(button, e, eOpts) {
        this.getFahrplanerView().hide();
        this.getMainView().show();
    },

    storeTest: function(button, e, eOpts) {
        this.stops.filter("id", 250);
    },

    onLineOneItemTap: function(list, index, item, record) {


        /*var dataView = this.getLineTwo();
        var linesData = record.get('lines');
        //var quantity = linesArray.getCount();



        var myPanel = Ext.create('Ext.Panel', {
            html: "<div class=\"buslineWrapper\"><div class=\"buslinesBoxLeft\"><div class=\"busIcon\" stlye=\"background-image:url(resources/images/icons/bus-icon-150x150.png)\"></div> " + this.getLines(linesData) + "</div><div class=\"buslinesBoxRight\">"+ record.get('name')+ "</div><div class=\"clearing\"></div></div>"
        });

        dataView.removeAll();
        dataView.add([myPanel]);*/
    },

    onFocusSearchfieldStart: function(textfield, e, eOpts) {

        //var searchTitle = Ext.getCmp('SearchTitle');
        //searchTitle.setData({title:"Start"}); // Übergabe an das Label searchTitle
        //console.log('Search Typ übergabe ::before');
        this.getApplication().getController('searchViewController').searchType = 'start';
        //console.log('Search Typ übergabe ::after');
        this.getSearchView().show({type:"slide",direction:"up"});
        this.getFahrplanerView().hide();
    },

    onFocusSearchfieldDestination: function(textfield, e, eOpts) {
        //var searchTitle = Ext.getCmp('SearchTitle');
        //searchTitle.setData({title:"Ziel"});  // Übergabe an das Label searchTitle
        //console.log('Search Typ übergabe ::before');
        this.getApplication().getController('searchViewController').searchType = 'destination';
        //console.log('Search Typ übergabe ::after');
        this.getSearchView().show({type:"slide",direction:"up"});
        this.getFahrplanerView().hide();

    },

    sucheVerbindung: function(button, e, eOpts) {
        var searchView = this.getApplication().getController('searchViewController');
        var sOrt = searchView.getStartOrt();
        var zOrt = searchView.getZielOrt();
        var db = this.getDb();
        var start = this.getStartOrt();
        var ziel = this.getZielOrt();

        console.log(sOrt);
        console.log(zOrt);


        db.transaction(function(tx) {
           tx.executeSql("select lat,long as lng from stops where name = '"+sOrt+"';", [], function(tx, res) {
                start.lng = res.rows.item(0).lng;
                start.lat = res.rows.item(0).lat;
                console.log(" s"+start.lng);
           });
           tx.executeSql("select lat,long as lng from stops where name = '"+zOrt+"';", [], function(tx, res) {
                ziel.lat = res.rows.item(0).lat;
                ziel.lng = res.rows.item(0).lng;
                console.log(ziel.lat+" z"+ziel.lng);
           });

            }, function(e) {
              console.log("ERROR: " + e.message);
            });
        db.transaction(function(tx) {
           tx.executeSql("Select lineId From stops, connections, lines Where stops.id = connections.stopId and connections.lineId=lines.id and stops.name = '"+sOrt+"' intersect Select lineId From stops, connections, lines Where stops.id = connections.stopId and connections.lineId = lines.id and stops.name = '"+zOrt+"';", [], function(tx, res)
           {
                var length = res.rows.length;
                var lines = [];
                var j=0;

                if(length===0){
                    console.log("verbindung über neumarkt");
                }else{
                    for(var i =0; i<length;i++){
                        console.log(res.rows.item(i).lineId);

                    }

                }
           });

            }, function(e) {
              console.log("ERROR: " + e.message);
            });





    },

    getLines: function(data) {
        /*var len = data.length;
        var content = '';
        content += '<div class="busline">';

        for(var i=0;i<len;i++){
            content += '<a href="#">';
            content += data[i]['LineId'];
            content += '</a>';

        }

        content += '</div>';

        return content;*/
    },

    launch: function() {

        Ext.getStore('stops').load();
        console.log("Store Stops wurde geladen.");
        this.dbcopy();




        var db = window.sqlitePlugin.openDatabase("vosnavigator.db");
        this.setDb(db);


        console.log("launcher Fahrplaner");
    },

    dbcopy: function() {

            window.plugins.sqlDB.copy("vosnavigator.db",function(){
                console.log("db wurde erfolgreich kopiert");},
                function(e){
                 //db already exists or problem in copying the db file. Check the Log.
                console.log("Error Code = "+JSON.stringify(e));
                //e.code = 516 => if db exists
                });

    }

});