/*
 * File: app/controller/goalsDetailsController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.controller.goalsDetailsController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            GoalsDetails: '#goalsDetails',
            detailsBackButton: 'button#detailsBackButton',
            GoalsView: '#GoalsView',
            dataviewDetails: 'dataview#dataviewDetails'
        },

        control: {
            "button#detailsBackButton": {
                tap: 'goalsDetailsBackButton'
            }
        }
    },

    goalsDetailsBackButton: function(button, e, eOpts) {
        this.getGoalsDetails().hide();
        this.getGoalsView().show();
    },

    setData: function(name, description, link) {
        Ext.getStore('leer').removeAll();
        var details = this.getDataviewDetails();
        details.refresh();


        details.setData({"name":name});
        details.setData({"description":description});
        details.setData({"link":link});
    }

});