/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            AchievementView: '#AchievementView',
            FahrplanerView: '#FahrplanerView',
            GoalsView: '#GoalsView',
            MainView: '#MainView',
            SettingsView: '#SettingsView',
            WeckerView: '#WeckerView',
            StartButton: '#StartButton'
        },

        control: {
            "button#StartButton": {
                tap: 'startButtonAction'
            }
        }
    },

    startButtonAction: function(button, e, eOpts) {
               alert("testButton");
    }

});