/*
 * File: app/model/stop.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VosNavigator.model.stop', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'longitudeOSM',
                type: 'float'
            },
            {
                name: 'latitudeOSM',
                type: 'float'
            },
            {
                name: 'longitude',
                type: 'float'
            },
            {
                name: 'latitude',
                type: 'float'
            },
            {
                convert: function(v, rec) {
                    if(v.line){
                        if(v.line instanceof Array){
                            return v.line;
                        } else{
                            return [v.line]; // Conversion to an Array
                        }

                        return v.line;
                    }
                },
                name: 'lines',
                type: 'auto'
            }
        ]
    }
});